- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Checking couchdb service is up
    become: yes
    become_method: sudo
    shell: service couchdb status
    register: couchdb_status
   
  - name: debug outuput to find "active" status
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BAX8DKSA3/Z8MVCo8SjbZnAMZJiPxKy4H5
      msg: couchdb status is working
    when: couchdb_status.stdout.find("active") != -1
