- hosts: "{{ servers }}"
  user: smartlis
  become: yes
  become_method: sudo
   
  tasks:
  - name: Checking couchdb service is up
    shell: service couchdb status
    register: couchdb_status
   
  - name: debug outuput to find "active" status
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BAX8DKSA3/Z8MVCo8SjbZnAMZJiPxKy4H5
      msg: couchdb is working
    when: couchdb_status.stdout.find("active") != 1
