- hosts: "{{ servers }}"
  user: smartlis
  become: yes
  become_method: sudo
  
  tasks:
  - name: Checking postgresql and couchdb services are up
    command: service "{{ item }}" status
    with_items:
      - couchdb
      - postgresql
    register: result
   
  - name: debug outuput to find "inactive" status
    debug: 
    var: result
