- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Checking postgresql service is up
    become: yes
    become_method: sudo
    command: service postgresql status
    ignore_errors: yes
