- hosts: {{ sldata_slave }}
  user: smartlis
  become: yes
  become_method: sudo
  
  tasks:
  - name: Create recovery.conf file
    user: postgres
    become: yes
    become_method: sudo
    file:
      path: /mnt/data/postgresql/9.6/main/recovery.conf
      state: touch
      owner: postgres
      group: postgres
      
  - name: Configure recovery.conf file
    blockinfile:
      path: /mnt/data/postgresql/9.6/main/recovery.conf
      content: |
        standby_mode = 'on'
        primary_conninfo = 'host="{{ sldata_master }}" port=5432 user=replication password="{{ replication_pass }}"'
        restore_command = 'cp /mnt/data/postgresql/9.6/main/archive/%f %p'
        archive_cleanup_command = 'pg_archivecleanup /mnt/data/postgresql/9.6/main/archive %r'
   
  - name: restart postgresql service
    service:
      name: postgresql
      state: restarted
   
