- hosts: sldatabase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
    
    - name: apt update
      become: yes
      apt:
        update_cache: yes

    - name: Install Erlang dependencies
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - build-essential
        - libmozjs185-1.0
        - libmozjs185-dev
        - libcurl4-openssl-dev
        - libicu-dev
    
    - name: Install erlang
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - erlang-dev=1:17.5.3
        - erlang-base=1:17.5.3
        - erlang-crypto=1:17.5.3
        - erlang-nox=1:17.5.3
        - erlang-inviso=1:17.5.3
        - erlang-runtime-tools=1:17.5.3
        - erlang-inets=1:17.5.3
        - erlang-edoc=1:17.5.3
        - erlang-syntax-tools=1:17.5.3
        - erlang-xmerl=1:17.5.3
        - erlang-corba=1:17.5.3
        - erlang-mnesia=1:17.5.3
        - erlang-os-mon=1:17.5.3
        - erlang-snmp=1:17.5.3
        - erlang-ssl=1:17.5.3
        - erlang-public-key=1:17.5.3
        - erlang-asn1=1:17.5.3
        - erlang-ssh=1:17.5.3
        - erlang-erl-docgen=1:17.5.3
        - erlang-percept=1:17.5.3
        - erlang-diameter=1:17.5.3
        - erlang-webtool=1:17.5.3
        - erlang-eldap=1:17.5.3
        - erlang-tools=1:17.5.3
        - erlang-eunit=1:17.5.3
        - erlang-ic=1:17.5.3
        - erlang-odbc=1:17.5.3
        - erlang-parsetools=1:17.5.3
