- hosts: sldatabase
  user: smartlis
    
  tasks:
  - name: Check response time
    command: psql -d sl_log -c "select case when cantidad<1 then 'OK' when cantidad<2 then 'Warning' else 'Danger' end AS Resultado from ( select count(*) Cantidad from public.sys_call_log where ms > 100 and date_part('day',dtcrea)=date_part('day',CURRENT_TIMESTAMP) and date_part('hour', dtcrea)=date_part('hour', CURRENT_TIMESTAMP)-1 	) AS Call_Log"
    ignore_errors: yes
    register: response_time
  
  - name: debug output to find response time >100ms
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BAX8DKSA3/Z8MVCo8SjbZnAMZJiPxKy4H5
      msg: "{{ response_time.stdout }}"
    when: response_time.stdout.find("{{ item }}") != -1
    with_items:
      - "Warning"
      - "Danger"
